/**
 * FPS Template Schema — Config variables for Advanced FPS template
 * Self-contained; no imports. Loaded by config when SCENE_TEMPLATE === 'fps'
 */

export const FPS_SCHEMA = [
  { category: 'TEMPLATE', name: 'SCENE_TEMPLATE', type: 'string', value: 'fps' },
  { category: 'TEMPLATE', name: 'PROJECT_NAME', type: 'string', value: 'MyProject' },
  { category: 'MAP', name: 'MOUSE_SENSITIVITY', type: 'number', value: 0.0002, min: 0.0001, max: 0.01, step: 0.0001 },
  { category: 'MAP', name: 'MAP_SIZE', type: 'number', value: 80, min: 10, max: 200, step: 10 },
  { category: 'MANTLE', name: 'MANTLE_ENABLED', type: 'number', value: 0, min: 0, max: 1, step: 1 },
  { category: 'MANTLE', name: 'MANTLE_MAP_SIZE', type: 'number', value: 256, min: 64, max: 512, step: 64 },
  { category: 'MANTLE', name: 'MANTLE_SCALE', type: 'number', value: 80, min: 20, max: 200, step: 10 },
  { category: 'MANTLE', name: 'MANTLE_ELEVATION', type: 'number', value: 10, min: 1, max: 50, step: 1 },
  { category: 'MANTLE', name: 'MANTLE_EROSION_ITER', type: 'number', value: 5000, min: 0, max: 100000, step: 5000 },
  { category: 'MANTLE', name: 'MANTLE_HEIGHTMAP_URL', type: 'string', value: '' },
  { category: 'CHARACTER', name: 'PLAYER_HEIGHT', type: 'number', value: 1.7, min: 0.5, max: 3, step: 0.1 },
  { category: 'CHARACTER', name: 'WALK_SPEED', type: 'number', value: 0.12, min: 0.01, max: 1, step: 0.01 },
  { category: 'CHARACTER', name: 'SPRINT_SPEED', type: 'number', value: 0.22, min: 0.01, max: 2, step: 0.01 },
  { category: 'CHARACTER', name: 'JUMP_FORCE', type: 'number', value: 0.15, min: 0, max: 1, step: 0.01 },
  { category: 'CHARACTER', name: 'GRAVITY', type: 'number', value: -0.008, min: -0.05, max: 0, step: 0.001 },
  { category: 'CHARACTER', name: 'AIR_DRAG', type: 'number', value: 0.98, min: 0.9, max: 1, step: 0.01 },
  { category: 'CHARACTER', name: 'APEX_THRESHOLD', type: 'number', value: 0.02, min: 0, max: 0.1, step: 0.01 },
  { category: 'CHARACTER', name: 'APEX_GRAVITY_MULT', type: 'number', value: 0.5, min: 0.1, max: 1, step: 0.1 },
  { category: 'CHARACTER', name: 'AIR_ACCELERATION', type: 'number', value: 0.4, min: 0.1, max: 1, step: 0.05 },
  { category: 'CHARACTER', name: 'GROUND_FRICTION', type: 'number', value: 0.85, min: 0.5, max: 1, step: 0.05 },
  { category: 'CHARACTER', name: 'FALL_RESPAWN_Y', type: 'number', value: -50, min: -500, max: 0, step: 10 },
  { category: 'CHARACTER', name: 'DRIFT_ENABLED', type: 'number', value: 0, min: 0, max: 1, step: 1 },
  { category: 'CHARACTER', name: 'DRIFT_SPEED_THRESHOLD', type: 'number', value: 0.08, min: 0.01, max: 0.5, step: 0.01 },
  { category: 'CHARACTER', name: 'DRIFT_GROUND_FRICTION', type: 'number', value: 0.92, min: 0.8, max: 1, step: 0.01 },
  { category: 'CHARACTER', name: 'DRIFT_TURN_MULT', type: 'number', value: 1.4, min: 0.5, max: 3, step: 0.1 },
  { category: 'WEAPONS', name: 'WEAPON_URL', type: 'string', value: 'https://dl.dropbox.com/s/wbia4zetn1bdeze/' },
  { category: 'WEAPONS', name: 'WEAPON_FILE', type: 'string', value: 'arms_assault_rifle_02.glb' },
  { category: 'WEAPONS', name: 'FIRE_RATE', type: 'number', value: 100, min: 10, max: 1000, step: 10 },
  { category: 'WEAPONS', name: 'RECOIL_STRENGTH_UP', type: 'number', value: -0.01, min: -0.1, max: 0, step: 0.001 },
  { category: 'WEAPONS', name: 'RECOIL_STRENGTH_BACK', type: 'number', value: -0.04, min: -0.2, max: 0, step: 0.01 },
  { category: 'WEAPONS', name: 'RECOIL_STRENGTH_SIDE', type: 'number', value: 0, min: -0.05, max: 0.05, step: 0.001 },
  { category: 'WEAPONS', name: 'RECOIL_RECOVERY', type: 'number', value: 0.15, min: 0.01, max: 1, step: 0.01 },
  { category: 'WEAPONS', name: 'TRACER_LENGTH', type: 'number', value: 0.5, min: 0.1, max: 2, step: 0.1 },
  { category: 'WEAPONS', name: 'RAY_LENGTH', type: 'number', value: 100, min: 10, max: 500, step: 10 },
  { category: 'COMPONENTS', name: 'WEAPON_SLOT', type: 'number', value: 0, min: 0, max: 1, step: 1 },
  { category: 'WEAPONS', name: 'WEAPON_SWITCH_KEY', type: 'number', value: 49, min: 0, max: 255, step: 1 },
  { category: 'WEAPONS', name: 'WEAPON_SWITCH_KEY_2', type: 'number', value: 50, min: 0, max: 255, step: 1 },
  { category: 'WEAPONS', name: 'WEAPON_WHEEL_KEY', type: 'number', value: 9, min: 0, max: 255, step: 1 },
  { category: 'COMPONENTS', name: 'ATTACHMENT_SCOPE', type: 'number', value: 0, min: 0, max: 3, step: 1 },
  { category: 'COMPONENTS', name: 'ATTACHMENT_MUZZLE', type: 'number', value: 0, min: 0, max: 1, step: 1 },
  { category: 'ATTACHMENTS', name: 'ATTACHMENT_CYCLE_SCOPE_KEY', type: 'number', value: 86, min: 0, max: 255, step: 1 },
  { category: 'ATTACHMENTS', name: 'ATTACHMENT_CYCLE_MUZZLE_KEY', type: 'number', value: 66, min: 0, max: 255, step: 1 },
  { category: 'ADS', name: 'BASE_HEAD_POS', type: 'Vector3', value: { x: -0.03, y: 0.04, z: -0.24 } },
  { category: 'ADS', name: 'ADS_HEAD_POS', type: 'Vector3', value: { x: -0.10, y: 0.07, z: 0.1 } },
  { category: 'ADS', name: 'CAM_GLOBAL_OFFSET', type: 'Vector3', value: { x: 0, y: 0, z: 0 } },
  { category: 'ADS', name: 'CAM_OFFSET_X', type: 'number', value: 0, min: -0.2, max: 0.2, step: 0.01 },
  { category: 'ADS', name: 'CAM_OFFSET_Y', type: 'number', value: 0, min: -0.2, max: 0.2, step: 0.01 },
  { category: 'ADS', name: 'BULLET_EMITTER_OFFSET', type: 'Vector3', value: { x: 0, y: 0, z: 0 } },
  { category: 'ADS', name: 'BULLET_EMITTER_ADS_OFFSET', type: 'Vector3', value: { x: 0, y: 0, z: 0 } },
  { category: 'ADS', name: 'CROSSHAIR_ALPHA_ADS', type: 'number', value: 0.3, min: 0, max: 1, step: 0.1 },
  { category: 'ADS', name: 'CROSSHAIR_ALPHA_HIP', type: 'number', value: 1.0, min: 0, max: 1, step: 0.1 },
  { category: 'ADS', name: 'CROSSHAIR_SCALE_ADS', type: 'number', value: 0.5, min: 0.1, max: 1, step: 0.1 },
  { category: 'ADS', name: 'CROSSHAIR_SCALE_HIP', type: 'number', value: 1.0, min: 0.5, max: 2, step: 0.1 },
  { category: 'ADS', name: 'SWAY_INFLUENCE', type: 'number', value: 5, min: 0, max: 10, step: 0.5 },
];
